### ISSUE TITLE
[2.0.1] Cannot centrifuge Forestry honeycombs

### ISSUE THREAD

**Issue by livenemo** [ArchitektRadim/ArchitPack-Greg-2#1]
Pack version: 2.0.1

Forestry centrifuge is disabled, but there's no other way to process them (via GTCE centrifuge?).

**Comment by ArchitektRadim** [comment]
Looks like major issue. Thanks for letting me know, going to fix it in next patch coming as soon as possible.

**Comment by ArchitektRadim** [comment]
Fixed in 2.1.0 (reintroduced Forestry Centrifuge which makes Gregicality register Honeycomb processing recipes in GTCE Centrifuge)
